### PR TITLE
GutterNode PCB Ready

### PR DESCRIPTION
**Pull request by jonsowman**
Happy with this? Changes since we last spoke:
- PWM and ADC broken out to 4x1 gpio header
- Added part numbers to top & bottom silk
- Added resistor and capacitor next to 4x1 gpio header to allow @mattbrejza rain sensor to be used
- ISET pin to AVR ADC pin, so charge current can be monitored

Gerbers viewable here: http://gerblook.org/pcb/pjUk9WNUQibm4QhBPkHd9P#front

### CODE REVIEW

**Comment by jonsowman** [comment]
OK, broken out UART to the 2 pin header near/under the DHT22. Labelled RX/TX.

Also a few other small changes, including grounding the bottom pad on the cn3083.

New gerbers: http://gerblook.org/pcb/A2qnLQDgeLtQNrsrDu7ZuP#front

**Comment by jamescoxon** [comment]
Looks good, we should get this sent off asap so we can roll out some proto nodes

**Comment by jonsowman** [comment]
gNode is 25mm tall and can't be squashed, so we can only fit one on a 50x50 panel (no room for slots between panels).

Have whipped up this CN3083 breakout so we can use it as a standalone LiPo charger for other nodes, or can distribute as required.

I'll put this and gNode on the same panel.

Gerbers: http://gerblook.org/pcb/Y7dsMk4LHWGYJ7eBR69uiS#front

**Comment by jonsowman** [comment]
@jamescoxon I was thinking JST connector for battery and then the BATT terminal connector for the load. Is that OK?

I wanted to make it clear that that is a direct connection to the battery, not regulated or anything.

**Pull request merged**
